
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Serhat Karaatay
 */
public class SiparisUygulamasi extends javax.swing.JFrame {
    Map<String, Integer> siparisler = new LinkedHashMap<String,Integer>();
    
    
    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender_box = new javax.swing.JCheckBox();
        beyti_box = new javax.swing.JCheckBox();
        salata_box = new javax.swing.JCheckBox();
        ayran_box = new javax.swing.JCheckBox();
        goster_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipariş Uygulaması");

        jLabel1.setText("MENÜ");

        iskender_box.setText("İskender - 250 TL");

        beyti_box.setText("Beyti - 300 TL");

        salata_box.setText("Salata - 50 TL");

        ayran_box.setText("Ayran - 30 TL");

        goster_button.setText("Siparişleri Göster");
        goster_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goster_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayran_box)
                    .addComponent(salata_box)
                    .addComponent(beyti_box)
                    .addComponent(iskender_box)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goster_button))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskender_box)
                .addGap(18, 18, 18)
                .addComponent(beyti_box)
                .addGap(18, 18, 18)
                .addComponent(salata_box)
                .addGap(18, 18, 18)
                .addComponent(ayran_box)
                .addGap(18, 18, 18)
                .addComponent(goster_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void siparisleriGoster(){
        String message = "";
        int tutar = 0;
        if(siparisler.isEmpty()){
            message = " Siparişiniz Bulunmamaktadır ";
        }
        else{
            message += "Siparişler\n";
            for(Map.Entry<String, Integer> entry : siparisler.entrySet()){
                message+= entry.getKey() + "\n";
                tutar += entry.getValue();
            }
            message += "Toplam Tutar : " + tutar + " TL";
        }
        JOptionPane.showMessageDialog(this, message);
    }
    private void goster_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goster_buttonActionPerformed
        
        if(iskender_box.isSelected()){
            siparisler.put("İskender",250);
        }
        else{
            siparisler.remove("İskender");
        }
        if(beyti_box.isSelected()){
            siparisler.put("Beyti",300);
        }
        else{
            siparisler.remove("Beyti");
        }
        if(salata_box.isSelected()){
            siparisler.put("Salata",50);
        }
        else{
            siparisler.remove("Salata");
        }
        if(ayran_box.isSelected()){
            siparisler.put("Ayran",30);
        }
        else{
            siparisler.remove("Ayran");
        }
        siparisleriGoster();
        
    }//GEN-LAST:event_goster_buttonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran_box;
    private javax.swing.JCheckBox beyti_box;
    private javax.swing.JButton goster_button;
    private javax.swing.JCheckBox iskender_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salata_box;
    // End of variables declaration//GEN-END:variables
}
